### ISSUE TITLE
Implement a Camo proxy for images

### ISSUE THREAD

**Issue by ameliaikeda** [StackExchange/stack-blog#122]
After some light discussion with @cky, I wondered: would it be possible for Stack Exchange to implement an image proxy (like Google and GitHub do), such as [atmos/camo](https://github.com/atmos/camo)?

I've currently got a Camo instance running in production, and GitHub do too; post any image anywhere on GitHub and it will be proxied through `https://camo.githubusercontent.com`.

It works by taking a URL, and using HMAC-SHA-1 with a shared key to cache-bust/rate-limit. The default key is usually `'0x24FEEDFACEDEADBEEFCAFE'`

This could technically also be used in production at Stack Exchange for posts themselves, but I gather that's a pretty big commitment. It's pretty battle-tested on GitHub, though.

An example is below:

```
http://puu.sh/8tN8V.png -> https://images.r-a-d.io/6bb5cb44d3d5c030784bce28172411bbd4bb1847/687474703a2f2f7075752e73682f38744e38562e706e67
```

If you guys want to go down this route, I'd make a `secure_image` helper for liquid that'd automatically HMAC and generate a new URL:

```
<img src="{{ page.avatar | secure_image }}" alt="{{ page.username }}">
```

**Comment by ameliaikeda** [comment]
For completeness, this'd have to be a liquid filter:

``` ruby
require 'openssl'
require 'config'

module StackExchange
  module SecureImage
    def secure_image(input)
      digest = OpenSSL::HMAC.hexdigest(
        OpenSSL::Digest.new('sha1'), config['camo_key'], input
      )
      image_url = digest.to_enum(:each_byte).map { |byte| "%02x" % byte }.join

      "#{config['camo_host']}/#{digest}/#{image_url}"
    end
  end
end

Liquid::Template.register_filter(StackExchange::SecureImage)
```

Usage:

```
{{ http://example.com/image.png | secure_image }}
```

**Comment by jc4p** [comment]
I'm having some difficulty understanding what the benefit of this would be -- We _should_ be only using i.stack.imgur images on the blog, which supports https://

**Comment by ameliaikeda** [comment]
This is merely for the edge cases (not all images in posts use imgur), but if you're going to be moving everything to imgur, then I guess this is redundant. Otherwise, there's still quite a lot of posts to migrate over. Avatar URLs in comments, too.

**Comment by ameliaikeda** [comment]
...Also I'm an idiot, and just remembered I was the one who changed avatar images to HTTPS. That point is moot now.

**Comment by ameliaikeda** [comment]
Closing because this can be solved without a proxy. It'd still be useful on SE sites, though.
