### ISSUE TITLE
iTunes looks for podcasts in blog.stackexchange.com/feed/podcast

### ISSUE THREAD

**Issue by hairboat** [StackExchange/stack-blog#130]
So we need a file there that tells iTunes where to look. 

That's as far as my expertise goes. :\

**Comment by JonHMChan** [comment]
Looks like we're missing a few XML tags and we need to upload these files somewhere http://www.apple.com/itunes/podcasts/specs.html#rss

Need to troubleshoot - looking in.

**Comment by gbrayut** [comment]
archive of the old feed is at https://web.archive.org/web/20130305092504/http://blog.stackexchange.com/feed/podcast

Nick is looking at rendering this in Jekyll

**Comment by m0sa** [comment]
fixed in ab21c1d213ce580ed418a59a6ecf727119bed397
