### ISSUE TITLE
Have to scroll to get any meaningful content on a 13" rMBP

### ISSUE THREAD

**Issue by rossipedia** [StackExchange/stack-blog#14]
There is a lot of wasted space going on here, and all the meaningful content is well below the fold when viewed at 1280x800 (std res for a 13" rMBP or MBA). 

![screen shot 2015-03-08 at 1 23 34 pm](https://cloud.githubusercontent.com/assets/96213/6547183/6bd1d00a-c596-11e4-8060-23cab427b685.png)

**Comment by JonHMChan** [comment]
Yeah, still working on the above fold content - going to have to fix sizing and talk it through with the designers

**Comment by JonHMChan** [comment]
Remove the large hero for now. Still need to go to the designers for overall comments.
