### ISSUE TITLE
Relative paths to old blog posts are mis-structured

### ISSUE THREAD

**Issue by hairboat** [StackExchange/stack-blog#159]
Discovered the problem in https://github.com/StackExchange/stack-blog/commit/eef48d55f5bb75739beb018f463bf8a9e310d7b5.

This is an old blog post that links to an older blog post, and somehow during the migration, that link was converted to a relative one - which turned out to be incorrectly structured, so it appeared the referenced post was lost. 

Robert (who authored the post originally) says he wouldn't have known how to make a relative link like that, so it must have been done by Wordpress or Jekyll, which leads me to believe there must be other posts with this problem. I'll see if I can dig some of them up as examples.

**Comment by gbrayut** [comment]
Searching for `](../` in the stack-blog/_posts folder says there are 20 matches in 13 files. I saved the details to a shared Google Spreadsheet at https://docs.google.com/spreadsheets/d/1dGjgEL2PZe6IrC34E-n4jlJzCcMUn3d98a01ZMjugkg/edit?usp=sharing

**Comment by hairboat** [comment]
OK, I'll go through and fix these manually next week (or so)

**Comment by hairboat** [comment]
All the links that turned up in Greg's search have been fixed
