### ISSUE TITLE
Comments have disappeared

### ISSUE THREAD

**Issue by AurelienGasser** [StackExchange/stack-blog#180]
While checking on my newly acquired worldwide fame, I realized the comments and recommendations have disappeared [on this post](https://blog.stackoverflow.com/2015/09/Stack-Spotlight-Aurelien-Gasser/). Where did the comments go? Why did they leave? Is the world falling apart?

**Comment by dgreenley** [comment]
I believe this occurred with the switch from blog.stackexchange.com back to blog.stackoverflow.com. Disqus has a domain migration tool which should be able to take care of it: https://help.disqus.com/customer/portal/articles/912627-domain-migration-wizard

Also, looking at https://disqus.com/home/forums/stackoverflowblog/ some of the articles listed are linking to the dev domain, which suggests some comments where made on dev, and could also be migrated.

**Comment by JonHMChan** [comment]
We used the Disqus migration tool that was mentioned and should have had everything moved over. Unless there are still major gaps, going to close.

**Comment by dgreenley** [comment]
The dev domain seems to have complicated things, unfortunately. For example: https://disqus.com/home/discussion/stackoverflowblog/stack_spotlight_aurelien_gasser_stack_exchange_blog_a_destination_for_all_things_related_to_developm/ shows a set of comments which is apparently linked to the old (SE) dev blog domain ... but they seem to be non-dev comments? I'm not seeing any comments for that post on the main or dev blog.

I don't know if all comments currently associated with dev.blog.stackexchange.com would also need to be migrated, or if some some were not intended for public consumption.
