### ISSUE TITLE
Avatar is an unoptimised image on the 'Benefits for Developers from San Francisco to Sweden' blog post

### ISSUE THREAD

**Issue by stijnherreman** [StackExchange/stack-blog#263]
http://stackoverflow.blog/2017/01/Benefits-for-Developers-from-San-Francisco-to-Sweden/ uses a 3339x3339 image of 2.5 MB, and is resized client-side to 50x50. Is it possible to use a smaller image?

(reported by someone else [here in chat](http://chat.meta.stackexchange.com/transcript/message/5688636#5688636))

**Comment by dotnetCarpenter** [comment]
The same here:
https://stackoverflow.blog/2017/06/12/new-kids-block-understanding-developers-entering-workforce-today/

The [profile picture](https://stackoverflow.blog/wp-content/uploads/2017/02/profile2017.jpg) is 50px*50px but **2.55MB and 3339px\*3339px!** Ahh - it's the same image 😅
