### ISSUE TITLE
Podcasts should go through Podtrac before they hit the feed

### ISSUE THREAD

**Issue by hairboat** [StackExchange/stack-blog#28]
We use [Podtrac](http://podtrac.com/) for analytics & such on the podcast. My understanding is that we do this by prepending `http://www.podtrac.com/pts/redirect.mp3/` to the soundcloud file URL before pushing it out to the feed - so our feed URL actually looks like `http://www.podtrac.com/pts/redirect.mp3/feeds.soundcloud.com/stream/XXXXXXXXX.m‌​p3`. 

I _think_ it's that simple, but Alex Miller knows more.

**Comment by JonHMChan** [comment]
Where exactly should this be? In our RSS feeds or in the posts themselves? Or both?

**Comment by hairboat** [comment]
This used to happen in podpress so I believe it just has to be in the feeds.

**Comment by m0sa** [comment]
I configured soundcloud so it prefixes the urls automatically in the source rss feed
