### ISSUE TITLE
Create an internal tool to manage image uploads and sizing

### ISSUE THREAD

**Issue by JonHMChan** [StackExchange/stack-blog#36]

**Comment by rossipedia** [comment]
I believe we pay for a custom instance from them: stack.imgur.com. Currently the only way to get images on to it is via API.

We should either set up a page somewhere to allow blog users to upload images to it, or get in contact with them to work out an upload form. 

Of course, we could also just set up an account on imgur.com directly.

**Comment by hairboat** [comment]
We do have an arrangement with imgur already - all photos on Q&A posts are hosted there. I usually lazy-upload by starting a new post and uploading from the editor. Would be cool to have a lightweight UI for this. s.tk/upload or something.

**Comment by bretcope** [comment]
Talk to a core dev. They might be able to create an upload page only accessible to employees which re-uses the existing code paths for uploading a file and getting the link.

**Comment by JonHMChan** [comment]
@ironyx is this something we can do?

**Comment by JonHMChan** [comment]
@jc4p is taking point on this, working on a UI that lets users upload, (optionally) slice, resize, and push to repo internally. Related issues https://github.com/StackExchange/blog/issues/35 https://github.com/StackExchange/blog/issues/24 https://github.com/StackExchange/blog/issues/20

**Comment by JonHMChan** [comment]
Spoke with @jc4p on this for a pretty straightforward implementation.

**Comment by JonHMChan** [comment]
@jc4p any progress on this front?

**Comment by jc4p** [comment]
We fucked bro

**Comment by JonHMChan** [comment]
I figured.

**Comment by haneytron** [comment]
I take it imgur corporate hosting is sunsetting us? Guess I know what I'm
working on when I return. ;)

**Comment by JonHMChan** [comment]
Until we figure out what in the seven kingdoms is going with Imgur, @rmaleady and I are using [GH Issues and their CDN to host](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/). Closing until we hear more.

**Comment by JonHMChan** [comment]
Reopening - apparently we're going to be able to continue using Imgur for the forseeable future. We still need to scrub posts and reupload. cc @rmaleady @jc4p

**Comment by haneytron** [comment]
Roll with it as imgur. If we do something else, there will be a long enough transition that it won't be that big of a deal to switch it. Program it to an interface or something though so it's an easy swap component. ;)

**Comment by jc4p** [comment]
@jonhmchan any requirements for max long edge/aspect ratio/etc?

I'm going to make all the uploaded images run through an image optimizer (pngcrush/something for JPGs), but do we have any non technical requirements for then pertaining to look and feel?

**Comment by JonHMChan** [comment]
@jc4p no non-technical requirements

**Comment by JonHMChan** [comment]
@jc4p ETA on when we can use the tool to do the image conversions?

**Comment by jc4p** [comment]
EOD

**Comment by jc4p** [comment]
Here's what the latest version of the code for this looks like:
![image](https://cloud.githubusercontent.com/assets/207575/7737646/8ced748e-ff1a-11e4-9540-7b6b76cd4d28.png)

You can then copy that URL and put it into your blog post.

The code for it lives in https://github.com/StackExchange/SEBlogImageUploader -- It's not hosted anywhere yet because I have absolutely 0 clue how to get something hosted internally and I was told that Heroku was bad. How do we do that side of it?

It's also using kraken.io to do the image resizing and image optimization stuff, right now it's on a free tier account, I'm not sure if we'll need to end up upgrading that account to a paid one or not.

**Comment by JonHMChan** [comment]
Taking it from here - I think I might just get this to be implanted into some part of Core (I also want us to pull in some authentication features that are already built in there). Going to chat with @ironyx about it.

**Comment by JonHMChan** [comment]
Done here: http://blogtools.ds.stackexchange.com/ (you need to be on the VPN or on the office network to access)
