### ISSUE TITLE
Update sidebar content on each channel

### ISSUE THREAD

**Issue by JonHMChan** [StackExchange/stack-blog#41]
So far, I've used the same generic copy on all the channels on the top of the sidebar. We may want to update this to reflect the specific channel: the engineering channel has open source contributions there, a bit more focused on our devs, etc.

**Comment by JonHMChan** [comment]
@ErinCorleyGray thoughts on this?

**Comment by ErinCorleyGray** [comment]
@JonHMChan You mean the Hello World part? I agree we could get more specific here; they've made it to that channel and already had the option to read that content on the homepage.

**Comment by JonHMChan** [comment]
Right - I think we can keep the Hello World piece for the engineering blog (that's what it was originally for) any idea what it should be for the Home Page and the for the Company New channel?

**Comment by ErinCorleyGray** [comment]
Eh, on second thought.....I keep forgetting that this is still mainly one audience, and that's developers and the current readers of the se/so blog. I think the current copy covers what we're doing with both channels overall....Is there anything specifically not mentioned that you would want to see in the homepage or company news section? If so, I can try to write up some copy.

**Comment by JonHMChan** [comment]
@ErinCorleyGray hm if you think it's ok that's fine with me - the only difference is that the types of content on each of the channels is different: company news is pretty broad to anyone to look at including press, the larger Q&A network, etc. while the engineering blog is pretty much only for engineers, designers, and sysadmins. I'll leave it to you whether you think we should change.

**Comment by ErinCorleyGray** [comment]
Alright, I see how the homepage could direct them to one or the other. I'll try to work on some alternatives tonight or tomorrow.

**Comment by ErinCorleyGray** [comment]
https://docs.google.com/document/d/1SyxMNJX_znrhyVTkl134CUlt6-jyw-ZHm-iiXkfO6jI/edit#heading=h.q0g1y367c51a

Created two options for each section. Let me know what you think! @hairboat would love your input as well, and we can circulate elsewhere, if we feel it necessary.

**Comment by JonHMChan** [comment]
Really like option 2 here - unless any objections, will swap out.

**Comment by ErinCorleyGray** [comment]
Yup, I think I like option 2 better. Let's see if Abby has any opinions.

**Comment by JonHMChan** [comment]
Updated with https://github.com/StackExchange/blog/commit/8dfdc67541b5283c796f4eab49df0e6e9fc58822

**Comment by hairboat** [comment]
(Just saw this and I also like option 2)
