### ISSUE TITLE
Pagination icons & Windows

### ISSUE THREAD

**Issue by jc4p** [StackExchange/stack-blog#45]
The characters `❮` and `❯` are used for navigation but with the current fonts they don't show up on my machine (Windows 8.1, Chrome 43.0.2357.45) -- Hilariously they show up here as I'm editing this bug report in the `<textarea>` but when I just view the bug report they don't show, so I'm not quite sure if we can simply fix it by changing the font or not.

![image](https://cloud.githubusercontent.com/assets/207575/7509616/fd7aa524-f460-11e4-9311-639d334e93d5.png)

**Comment by JonHMChan** [comment]
Those should actually be SVG sprites anyways

**Comment by JonHMChan** [comment]
Done with https://github.com/StackExchange/blog/commit/ec84cee8a5a911653f48f5ecf152469f3cb0a66e
