### ISSUE TITLE
Footer links don't go anywhere

### ISSUE THREAD

**Issue by df07** [StackExchange/stack-blog#46]
![screen shot 2015-05-11 at 5 28 27 pm](https://cloud.githubusercontent.com/assets/1399498/7575485/24e8b308-f803-11e4-95ce-00d2609e7f1c.png)

They all just link to `#`

**Comment by JonHMChan** [comment]
Fixed with https://github.com/StackExchange/blog/commit/28ce1c4cc3ac71c4e3c7478e49fae82cacefbff4
