### ISSUE TITLE
`serverfault.com` tag leads to 404

### ISSUE THREAD

**Issue by df07** [StackExchange/stack-blog#47]
http://dev.blog.stackexchange.com/tags/serverfault.com

Presumably because of the '.com' in the URL.

**Comment by JonHMChan** [comment]
Fixed with https://github.com/StackExchange/blog/commit/2e85bd38375fe538a94fa34d0946955d8ab9a09d and https://github.com/StackExchange/blog/commit/27294953957ba6b0e5d622cde8d56df601f99712
