### ISSUE TITLE
Make sure Core integrations work for community bulletin and /blogs

### ISSUE THREAD

**Issue by JonHMChan** [StackExchange/stack-blog#49]
There are some integrations with community bulletin and /blogs. Spoke with @aalear about it.

**Comment by aalear** [comment]
The parsing works, but there are a few minor issues to iron out:
- The feed is missing post author information. Currently stackexchange.com parses that out out of dc:creator nodes (_not_ <author>).
- What happened to categories? Specifically, on Q&A sites we skip posts in "stackoverflow" category on non-SO/MSO sites' community bulletins. We need to maintain that. Example post: the dev survey results. The "stackoverflow" category/tag is missing on the new blog and needs to be preserved.

**Comment by JonHMChan** [comment]
Both issues should be fixed with https://github.com/StackExchange/blog/commit/87173d85a66772cad5e4f7699d6684d484fd4ca0 - verify?

**Comment by aalear** [comment]
Looks right, will check parsing in a few. However, the actual posts are missing the "stackoverflow" category. Was that a migration omission?

**Comment by JonHMChan** [comment]
Ew that's annoying. Just the one post I could find: https://github.com/StackExchange/blog/commit/a8947f825df5efccc5411b3d6e3c8611dd1ea9be
