### ISSUE TITLE
Page navigation and layout on author pages is wonky

### ISSUE THREAD

**Issue by Shog9** [StackExchange/stack-blog#53]
Ref: http://dev.blog.stackexchange.com/authors/jeffatwood/#page47

Page navigation appears in the header:

![header page nav](https://cloud.githubusercontent.com/assets/4950451/7642871/b966f7ba-fa51-11e4-8b60-deea72823f70.png)

...while the page _count_ and current page indicator are in the footer:

![footer page indicator](https://cloud.githubusercontent.com/assets/4950451/7642856/a233148e-fa51-11e4-892d-30466d44d53c.png)

Besides just being awkward having these two _closely_ related UI elements positioned so far from each other, the latter is sorta... intruding. Should either put both in the header, or create space in/above the footer for them.

**Comment by JonHMChan** [comment]
Oh that's...definitely not supposed to happen.

**Comment by JonHMChan** [comment]
This is strange - I actually can't repro. What browser are you using?

**Comment by JonHMChan** [comment]
No reproduction
