### ISSUE TITLE
Footer link to sites list is wrong

### ISSUE THREAD

**Issue by Shog9** [StackExchange/stack-blog#54]
![image](https://cloud.githubusercontent.com/assets/4950451/7642968/7d0637bc-fa52-11e4-8a79-140c27e355d6.png)
## Two problems with https://www.stackexchange.com/sites
1. No HTTPS support for SE.com
2. No www. prefix

**Comment by JonHMChan** [comment]
Fixed with https://github.com/StackExchange/blog/commit/8bf5d91f94d476921df7ff25130d490a098ccc1f
