### ISSUE TITLE
Back navigation doesn't work for paging

### ISSUE THREAD

**Issue by Shog9** [StackExchange/stack-blog#55]
Steps to reproduce:
1. Go to the homepage
2. Click "OLDER ARTICLES" to navigate to the second page
3. Try to navigate back to the first page, either by clicking your browser's back button or using the keyboard shortcut for the same.
4. Note that while you're now looking at a _different part_ of Page 2, you're still on Page 2. Confusingly, the URL fragment has changed to `#page1`

Also happens on author pages.

Probably also worth mentioning that trying to navigate _directly_ to a page by editing the URL fragment (for instance, to `#page45`) doesn't do anything unless you _refresh the page_ after submitting. 

If we're gonna be doing ajax loading for this, I'm thinking we need some popstate and hashchange handlers here.

**Comment by JonHMChan** [comment]
Fixed with https://github.com/StackExchange/blog/commit/e935a7d26c8b143fac96573d1137baba11ff9ae7
