### ISSUE TITLE
Page navigation shows me the end of the next page

### ISSUE THREAD

**Issue by Shog9** [StackExchange/stack-blog#56]
Steps to reproduce:
1. Go to the homepage
2. Click "OLDER ARTICLES" to navigate to the second page
3. Note that you're now looking at the _end_ of Page 2 (unless you didn't have images cached, in which case you're looking at _somewhere near the end but not quite *_at*\* the end\* of Page 2.

Debated whether or not to report this, since it _could_ be useful on occasion for quickly paging as the page navigation links remain visible (unless there are uncached images that load after the page scrolls). But this seems like an odd use-case.

**Comment by JonHMChan** [comment]
Yeah I had noticed this too and had a similar debate. I think there's going to be other ways of navigating quickly to other posts if you're looking quickly though, so I'm implementing a `$(window).scrollTop(0)` with page changes with https://github.com/StackExchange/blog/commit/6e25fc24314b900326a0ee3ce79fe98c0728129a
