### ISSUE TITLE
No paging for tags

### ISSUE THREAD

**Issue by Shog9** [StackExchange/stack-blog#57]
Go to a tag that has lots of posts in it, like [podcasts](http://dev.blog.stackexchange.com/tags/podcasts/) or [company](http://dev.blog.stackexchange.com/tags/company/).

Note the complete absence of page navigation.

You can load other pages by manually entering the URL fragment (for instance, `#page6`) and then refreshing. But that's not exactly obvious.

**Comment by JonHMChan** [comment]
Fixed with https://github.com/StackExchange/blog/commit/f81eb0e70e8ad1d33d57dd5dd42c2707abc35902
