### ISSUE TITLE
No podcast feed

### ISSUE THREAD

**Issue by Shog9** [StackExchange/stack-blog#58]
On the existing blog, there's a feed: http://blog.stackoverflow.com/feed/

On the new blog, there's a corresponding feed: http://dev.blog.stackexchange.com/feed/

On the existing blog, there's a feed for podcasts: http://blog.stackoverflow.com/category/podcasts/feed/

On the new blog, there is not: http://dev.blog.stackexchange.com/category/podcasts/feed/

We get a fair number of hits on that feed. Apparently there are programs that allow people to subscribe to podcasts for the purpose of listening to them on mobile devices; anyway, we should try not to break that link.

Also, it would be handy to have feeds for tags in general.

**Comment by JonHMChan** [comment]
Ah I will definitely add this in. You're right - do not want to regress here.

**Comment by JonHMChan** [comment]
Restored here: https://github.com/StackExchange/blog/commit/b66386e99db700270f87fbeba20752ef65f95f66

Making a separate issue for restoring xml feed on the other categories
