### ISSUE TITLE
Images stretched incorrectly

### ISSUE THREAD

**Issue by df07** [StackExchange/stack-blog#62]
From http://dev.blog.stackexchange.com/2015/06/stack-overflow-in-portuguese-now-with-less-beta/

![screen shot 2015-06-29 at 4 33 32 pm](https://cloud.githubusercontent.com/assets/1399498/8417763/9d83eba8-1e7c-11e5-9af5-d52e52be765e.png)

**Comment by JonHMChan** [comment]
Some width and height attributes remained from the port that's screwing up the CSS. Fixed with https://github.com/StackExchange/blog/commit/87bc640bd6100b28a1062986f5972e34df08dc9a
