### ISSUE TITLE
Gravatars rendered incorrectly

### ISSUE THREAD

**Issue by df07** [StackExchange/stack-blog#64]
Should append `?s=48&d=identicon&r=PG&f=1` to the end to get the correct size and request identicon by default instead of the gravatar logo.

![screen shot 2015-06-29 at 4 35 27 pm](https://cloud.githubusercontent.com/assets/1399498/8417805/e4574606-1e7c-11e5-9586-f3f9e1837dc3.png)

**Comment by JonHMChan** [comment]
Fixed with https://github.com/StackExchange/blog/commit/552777ac21be660f3ac42f159affaf062bf00e39
