### ISSUE TITLE
Move metadata below the title

### ISSUE THREAD

**Issue by Undo1** [StackExchange/stack-blog#68]
Quick mockup of what I'm thinking, which IMO looks a tad bit better (or at least more standard):

![screen shot 2015-07-01 at 3 15 15 pm](https://cloud.githubusercontent.com/assets/5162342/8465032/0149acd0-2004-11e5-8a28-4bd89dbb02a8.png)

**Comment by haneytron** [comment]
This gets my vote. More intuitive to me.
