### ISSUE TITLE
Comments are affected by URL parameter

### ISSUE THREAD

**Issue by normalhuman** [StackExchange/stack-blog#76]
The comments displayed at 
http://blog.stackexchange.com/2015/07/the-new-stack-exchange-blog/?cb=1
and at 
http://blog.stackexchange.com/2015/07/the-new-stack-exchange-blog/
are different, even though the post is the same one. It appears that Disqus is treating the URL parameter cb=1 as something that distinguishes between posts. 

(The parameter cb=1 is appended by the Community Bulletin on SE sites)

**Comment by jc4p** [comment]
Looks like this is also causing https:// URLs to get their own comment threads. Fixing...

**Comment by jc4p** [comment]
@JonHMChan are you the Disqus admin? Can you add me to that group too? This issue is now fixed but we now have 3 different comment threads going on for your blog post form earlier today (1 comment on `?cb=1`, 1 comment on `https://`) and I'd like to merge them, if possible.
