### ISSUE TITLE
Background color support for Steam browser

### ISSUE THREAD

**Issue by JonHMChan** [StackExchange/stack-blog#78]
background-color is removed as a property if I understand correctly. @ironyx has some details I think

**Comment by haneytron** [comment]
Photos attached of what the blog looks like in steam browser.

![Home Page](https://cloud.githubusercontent.com/assets/5252983/8478234/0c36758e-209e-11e5-9b82-0283f11cef52.png)
![Announcement Blog Post](https://cloud.githubusercontent.com/assets/5252983/8478235/0c451e36-209e-11e5-84ab-c5f085726c6c.png)

**Comment by haneytron** [comment]
It appears to be that the `body` tag needs `background-color` CSS applied. When I test my website in Steam (http://www.dache.io) it works properly, and this is the only difference I can see.

**Comment by JonHMChan** [comment]
Should be fixed with https://github.com/StackExchange/blog/commit/a2dd8b912f7bc05ec7eb39f6e8a0f93deca50055

**Comment by haneytron** [comment]
Confirmed fixed. Thanks!

![Fixed](https://cloud.githubusercontent.com/assets/5252983/8481510/7dea55fc-20b1-11e5-876d-eaefaac026b9.png)
