### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by donkirkby** [StackExchange/stack-blog#81]
If someone else forks your repository, it shows up in their list as `joeuser/blog`. I would suggest you put Stack Exchange in the name so it's obvious what they are contributing to. Renaming a GitHub repository sets up all the correct forwarding, so you don't have to worry about breaking links.

I suggest blog.stackexchange.com or stack-exchange-blog.

**Comment by NickCraver** [comment]
+1 on this - it's actually an issue for anyone, even devs working here on large enough changes to warrant a pull request.

**Comment by rossipedia** [comment]
`stackexchange/stack-blog` ?

**Comment by NickCraver** [comment]
@rossipedia yeah sure...I have no strong opinions here, just that it should have _some_ identifier. I currently have it as `stack-exchange-blog` locally, but IMO `stack-blog` equally accomplishes all I need as a dev: just some differentiation.

**Comment by donkirkby** [comment]
Works for me.

**Comment by JonHMChan** [comment]
Done.
