### ISSUE TITLE
Missing image on blog

### ISSUE THREAD

**Issue by ocoster-se** [StackExchange/stack-blog#86]
Missing image here:

https://blog.stackexchange.com/2011/01/welcome-valued-associate-nick-craver/

**Comment by alexwlchan** [comment]
This seems to be part of a larger problem where images within links haven’t survived the conversion – see issue #94

**Comment by NickCraver** [comment]
@gbrayut  has rescued the actual files from the old blog install for us - they're not lost and we'll figure out the best way to fix them up.

**Comment by jc4p** [comment]
I just did a mass migration of all of our old blog assets, this should be fixed now.
