### ISSUE TITLE
Links to blog.stackoverflow.com should be changed to blog.stackexchange.com

### ISSUE THREAD

**Issue by alexwlchan** [StackExchange/stack-blog#97]
The URLs are redirecting (good), but those links could all be updated to point to their new blog.stackexchange.com addresses, saving everybody a redirect (better).

I would do this myself, but that’s over 500 posts, and I think somebody who understands the mechanics of the redirect should do it, so that a bunch of previously working redirects don’t suddenly get replaced by broken links.

**Comment by JonHMChan** [comment]
This is a known issue, but there are some internal discussions that may affect this issue. Deferred for now, will re-open pending those developments.
